#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

panel_link("certificate", "manager");

for  my $event (qw(
    certificate-revert
    ))
{
    event_link("revert_ssl_certificate",$event,"10")
}

