#! /usr/bin/perl -w
use strict;
use warnings;

    system("/sbin/e-smith/db configuration delprop modSSL crt");
    system("/sbin/e-smith/db configuration delprop modSSL key");
    system("/sbin/e-smith/db configuration delprop modSSL CertificateChainFile");
    system("/sbin/e-smith/expand-template /home/e-smith/ssl.pem/pem");
    system("/sbin/e-smith/expand-template /etc/httpd/conf/httpd.conf");
    system("/sbin/service httpd-e-smith restart");
    system("/sbin/e-smith/signal-event ldap-update");
    system("/sbin/e-smith/signal-event email-update");
    exit
